name: "Navidrome Rating Sync"
version: "1.0.2"
slug: "subsonic-rating-sync"
description: "Syncing 5-star ratings and favorites (LOVE RATING) between audio files and Navidrome. Supported sync modes: two-way, one-way (Files → Navidrome), or (Navidrome → Files)."
url: "https://github.com/theodorx7/ha-subsonic-rating-sync"
arch:
  - aarch64
  - amd64
startup: application
boot: manual
init: false
#hassio_api: true
#homeassistant_api: true
map:
  - media:rw

options:
  server_protocol: "https"
  server_host: "musicfx.duckdns.org"
  server_port: 4533
  user: "test"
  password: "test"
  music_folder_id: "2"
  music_folder: ""
  sync_mode: "two-way"
  conflict_resolution: "server_wins"
  sync_interval_minutes: "1500"
  dry_run: true
  debug: true
schema:
  server_protocol: list(https|http)
  server_host: str
  server_port: int?
  user: str
  password: password
  music_folder_id: str
  music_folder: str?
  sync_mode: list(two-way|file-to-server|server-to-file)
  conflict_resolution: list(server_wins|file_wins)
  sync_interval_minutes: int?
  dry_run: bool
  debug: bool
  
