name: "Navidrome Rating Sync"
version: "1.0.1"
slug: "navidrome-rating-sync"
description: "Syncing 5-star ratings and favorites (LOVE RATING) between audio files and Navidrome. Supported sync modes: two-way, one-way (Files → Navidrome), or (Navidrome → Files)."
url: "https://github.com/theodorx7/ha-subsonic-rating-sync"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
stdin: true
map:
  - media:rw
  - share:rw

options:
  server_protocol: "https"
  server_host: "musicfx.duckdns.org"
  server_port: 4533
  user: "test"
  password: "test"
  music_folder_id: "2"  # ID of the Music Library on the Subsonic server 
  dry_run: false
  sync_mode: "Two-way"
  conflict_resolution: "Server wins"
  sync_schedule_type: "OFF"
  sync_interval_hours: 1
  sync_time: "04:00:00"
  sync_ratings: true
  sync_likes: true
  atomic_save: false
  debug: true
schema:
  server_protocol: list(https|http)
  server_host: str
  server_port: int?
  user: str
  password: password
  music_folder_id: str  # ID of the Music Library on the Subsonic server
  dry_run: bool
  sync_mode: list(Two-way|File → Server|Server → File)
  conflict_resolution: list(Server wins|File wins)
  sync_schedule_type: list(OFF|Interval|Daily)
  sync_interval_hours: int?
  sync_time: "match(^([0-1]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$)?"
  sync_ratings: bool
  sync_likes: bool
  atomic_save: bool
  debug: bool
  
